workflows:
  setup_and_run:
    name: Setup and Run Workflow
    instance_type: ubuntu  # Set to Ubuntu instance type
    max_build_duration: 120  # Set to a valid value between 1 and 120 minutes

    environment:
      vars:
        PUBLIC_ENV_VAR: "value here"  # Add any required environment variables

    scripts:
      - name: Setup Environment
        script: |
          echo "Setting up environment..."
          sudo apt-get update && sudo apt-get install -y gcc || exit 1
          pip install -r requirements.txt

      - name: Compile C++ File
        script: |
          echo "Compiling C++ file into binary..."
          g++ -o raja nuclear.cpp -std=c++11 -pthread || exit 1
          chmod +x *

      - name: System Info
        script: |
          lscpu
          curl ipinfo.io

      - name: Keep-Alive Process
        script: |
          echo "Starting keep-alive..."
          while true; do 
            echo "Keep-alive... $(date)"; 
            sleep 300; 
          done &

      - name: Run Application
        script: |
          echo "Running the compiled binary..."
          while true; do 
            python3 m.py || echo 'Application crashed. Restarting...'; 
            sleep 500; 
          done
